AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: disable
  Exclude:
    - 'Rakefile'
    - 'fakturoid.gemspec'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
      - 'test/**/*'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/CaseIndentation:
  IndentOneStep: true

Style/SignalException:
  EnforcedStyle: only_raise

Layout/TrailingWhitespace:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/NegatedIf:
  Exclude:
    - 'lib/fakturoid/response.rb'

Naming/MemoizedInstanceVariableName:
  Exclude:
    - 'lib/fakturoid/api.rb'

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Style/RescueStandardError:
  Exclude:
    - 'test/response_test.rb'

Style/TrivialAccessors:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false
