version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.3
        environment:
          TZ: /usr/share/zoneinfo/Europe/Prague
    steps:
      - checkout
      - run:
          name: Install gems
          command: bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: Run tests
          command: bundle exec rake test

      - restore_cache:
          key: rubocop-cache-{{ .Branch }}-{{ checksum ".rubocop.yml" }}
      - run:
          name: Run robocop
          command: bundle exec rubocop --fail-level C
      - save_cache:
          key: rubocop-cache-{{ .Branch }}-{{ checksum ".rubocop.yml" }}
          paths:
            - tmp/cache/rubocop_cache
